firebase/firebaseui-web

README.md
Just missing a capital T on 223.  And I thought well, why not.
=> Fix a typo on line 223 of readme.md

.travis.yml, README.md, protractor.conf.js
Only one node environment is tested now, the latest 6.x version.
Added Travis Build status to the Readme.
Tests were timing out on some browsers - increased the Jasmine default timeout to 5 minutes.
=> Fixed Travis configuration and tests.

changelog.txt, javascript/ui/page/signin.js, javascript/ui/page/signin_test.js, javascript/utils/idp.js, javascript/widgets/handler/signin.js, javascript/widgets/handler/signin_test.js, soy/pages.soy
Updated changelog.txt with latest changes before pushing a release.
Added a cancel button in the signin handler.
=> changelog.txt update and added sign in handler cancel button

README.md
The demo is a bit hard to find right now. This way, people can see what FirebaseUI is/looks like before getting into installation/usage details.
=> Make demo prominent in the README

gulpfile.js
At the moment only `require('firebase/app');` and `require('firebase/auth')` is needed but the Node distro imports the whole Firebase SDK with `require('firebase');`.
This makes it hard to only load parts of the Firebase SDK or use dynamic imports when using Node to build for the client (using Webpack for instance).
In this PR I'm replacing the `firebase` import with importing `firebase/app` and `firebase/auth`.
This would fix https://github.com/firebase/firebaseui-web/issues/163
=> Restrict firebase imports in Node distro

demo/README.md
I might have missed something, but this seems to be missing.
Install dependencies with `npm install` before trying to run the demo.
=> npm install

gulpfile.js
=> Using default attribute of Firebase require statement if available

.travis.yml, buildtools/run_tests.sh, package-lock.json, package.json, protractor.conf.js, protractor_spec.js, sauce_browsers.json
Upgrades tests to Node 8.
Upgrades protractor to the latest version.
Switches from phantomjs to headless chrome.
Adds various new timeouts to decrease likelihood of failure.
Adds new criteria for test retry, though this needs more confirmation.
=> Fixes failing CI tests

buildtools/run_tests.sh
External developers can only create PR from their own fork, in which they don't have access travis environment variables. It cause saucelabs test to fail. Disabled the test if saucelabs tests are running from travis and those variables are not available.
=> disable saucelab test if travis enviorment vars are not available

gulpfile.js, package-lock.json
`gulp.parallel(...localeDependencies)`
Becomes
`gulp.parallel.apply(null, localeDependencies)`
=> Replaces spread syntax with node 6 compliant syntax.

.travis.yml, gulpfile.js, package-lock.json
- reverted to node 6 for travis test since internal Jenkins builder uses node 6
- removed extra comma in gulp script
=> revert to node6 on travis and remove extra comma in gulp

gulpfile.js
Run build task in series instead of in parallel since build-npm depends on build-js.
=> change gulp build to use series task

sauce_browsers.json
disabled saucelabs test on ie10, ios9 and safari8
=> disabled saucelabs test on ie10, ios9 and safari8

gulpfile.js, package-lock.json, package.json
Fixes #618 
Instead of bundling the dependencies for the ES module, let's import them. This fixes the issue of `dialog-polyfill` also defining an export and bundlers getting confused.
I tried to run the tests, but ran into issues with PhantomJS, so if anyone from the team could run the tests, that would be nice.
=> Remove dependencies from ES module

README.md
cdn.firebase.com is old - we should be pointing at the new gstatic service
=> Update the cdn link to use gstatic

soy/elements.soy
Included id's on all input elements that have a label. This enables screen readers to correctly state to their users what is expected to be entered in each input.
=> Added id attribute to all input elements

javascript/widgets/handler/common.js, javascript/widgets/handler/common_test.js
Fixes issue when email link user tries to sign in with FirebaseUI when only email/password sign in method is provided.
In this case, we should just fallback to unsupported provider screen.
Fixes https://github.com/firebase/firebaseui-web/issues/708
=> Fixes issue when email link user is locked out

CHANGELOG.md, README.md, externs/firebaseui-externs.js, firebaseuihandler/README.md, javascript/widgets/config.js, javascript/widgets/config_test.js, javascript/widgets/uihandlerconfig_test.js, soy/elements.soy, soy/elements_test.js, soy/pages.soy, soy/pages_test.js, soy/pages_test_dom.html, types/index.d.ts
Allow customization of native providers.
In addition, allow ability to override the entire button label via "fullLabel".
This will be used instead of "Sign in with $providerName" for the long name.
However, for the short name, $providerName is still used.
=> Adds ability to customize IdP buttons.

package-lock.json, package.json
Fix 5 High Severities under following two issues:
1. https://npmjs.com/advisories/1550 --> "url-regex" all versions have this risk, the recommended way of changing requirement to "url-regex" to "url-regex-safe" wouldn't pass the test.
2. https://npmjs.com/advisories/1561  --> fix by installing node-forge version 0.10.0 and put that into package-lock.json
By installing corresponding packages, and edit versions inside package-lock.json.
Since npm install won't install newest versions but just meeting criteria to requirement, running npm install again would change my manual definitions in package-lock.json.
If current solution isn't good enough, I'll try update version for packages on the root(to see if that could raise the requirement of versions for its dependencies)
The root package for …
=> Fix high severities

CHANGELOG.md, javascript/testing/auth.js, javascript/widgets/authui.js, javascript/widgets/authui_test.js, package-lock.json
This is the followup from https://github.com/firebase/firebaseui-web/pull/802#pullrequestreview-576962077 and cl/352021214
=> Add emulator support for auth

buildtools/publish.sh
In recent 2,3 releases. Npm install can't ensure package-lock.json to be unchanged during running publish scripts,
the error usually I get is: Step #11: npm notice created a lockfile as package-lock.json. You should commit this file.
However, this error in highly randomness and would delay the release for 1-2 commits each time, and greatly reduce success rate for releasing. 
In the most recent release run, npm install change a package version back by 0.01, however, a second npm install would change it back and that doesn't happen on my local repo. This minute randomness cause release failure.
Therefore, I recommend using npm ci for reliable builds on package-lock.json.
Meanwhile, check/update package version using npm install before commit to update package-lock.json in time.
=> use npm ci to replace npm install

CHANGELOG.md, externs/firebaseui-externs.js, types/index.d.ts
Updates signInFailure's return type to also include void to match external documentation.
Fixes https://github.com/firebase/firebaseui-web/issues/770
=> fix: fixes signInFailure return type

README.md
I followed this great guide, but hit trouble when I inserted the initialization snippet because it doesn't include the firebase-auth SDK. After searching, I found the firebase-auth SDK CDN is shown here: https://firebase.google.com/docs/web/setup.
=> Update README.md to include CDN download of firebase-auth JS SDK.

buildtools/generate_test_files.sh, package-lock.json, package.json
In [Closure Library](https://github.com/google/closure-library), we will be removing `depswriter.py` and other Python-based build scripts soon. `depswriter.py` is superceded by [`google-closure-deps`](https://www.npmjs.com/package/google-closure-deps), a similar tool we maintain that is implemented in Node.js.
Here, I've substituted the `depswriter.py` command with a corresponding command from `google-closure-deps`; the CLI flags are similar. The difference in output is minimal (see below).
Explanation of "extra" flags:
* `--closure-path="node_modules/google-closure-library/closure/goog"` Path to Closure (now required)
* `--file="node_modules/google-closure-library/closure/goog/deps.js"` Use the deps.js file bundled with Closure as part of deps calculation
* `--exclude=...` Not strictly …
=> Use google-closure-deps instead of depswriter.py.

README.md
Documents hash routing incompatibility with email link sign in.
Fixes https://github.com/firebase/firebaseui-web/issues/537
=> fix: hash routing incompatibility with email link

README.md
AdminRestrictedOperation field is only for GCIP projects.
[#859](https://github.com/firebase/firebaseui-web/issues/859)
=> Fix: Update GCIP docs on corresponding settings.

CHANGELOG.md, README.md, externs/firebaseui-externs.js, javascript/utils/account.js, javascript/widgets/authui.js, javascript/widgets/authui_test.js, javascript/widgets/config.js, javascript/widgets/exports_app.js, javascript/widgets/handler/providersignin_test.js, types/index.d.ts
Update Readme.md, and remove all `accountchooser.com` related configs and enums.
=> Shut down accountchooser credential helper

packages/core/src/auth.ts, packages/core/src/behaviors.test.ts, packages/core/src/behaviors.ts, packages/core/src/config.test.ts, packages/core/src/config.ts
This PR adds support for the `recaptchaVerification` behavior, and also allows for default behaviors in core to ensure it's always present.
=> feat(core): Support recaptchaVerification behavior

packages/core/src/index.ts, packages/core/src/register-framework.test.ts, packages/core/src/register-framework.ts, packages/react/src/index.ts
Adds an internal API called `registerFramework` which sets a component within the firebase js sdk for tracking
=> feat(core): Add registerFramework util

packages/core/src/behaviors/anonymous-upgrade.test.ts, packages/core/src/behaviors/anonymous-upgrade.ts, packages/core/src/behaviors/index.test.ts, packages/core/src/behaviors/index.ts
Supports allowing the users to define a callback which is called on a successful account upgrade:
```
autoUpgradeAnonymousUsers({
onUpgrade: (ui, oldUserId, cred) => {
// Perform some async logic to merge accounts for example.
},
})
```
=> feat(core): Support autoUpgradeAnonymousUsers onUpgrade callback

packages/core/src/auth.test.ts, packages/core/src/auth.ts, packages/react/src/auth/forms/phone-auth-form.test.tsx, packages/react/src/auth/forms/phone-auth-form.tsx
This PR changes `signInWithPhoneNumber` to `verifyPhoneNumber` - this allows us to reuse the functionality for MFA flows, without needing to create an additional function specifically for MFA.
=> refactor(core,react): signInWithPhoneNumber -> verifyPhoneNumber
