javascript/widgets/handler/starter_test.js, protractor.conf.js, sauce_browsers.json
Updated browsers list with newer recent of Firefox and Chrome, and added mobile browsers.
=> Added more browsers coverage

README.md, demo/public/index.html, demo/public/widget.html
- Updated CDN links.
- Added NPM and Bower installation instructions.
=> Updated README after new release.

README.md
- Added missing closing bracket in one of the code snippet.
- Removed useless quotes in code snippets.
- Changed display of the Configuration table to render it better.
- Fixed line size to use 80 everywhere. Some exceptions remain for tables, links, headings and code blocks.
=> Fixed README issues

README.md, demo/public/index.html, demo/public/widget.html, package.json
Added an `npm run prepublish` command to prepare the demo.
=> Updated readme to link to release notes, and updated demo

README.md
=> Updated readme to mention the localhost IE11 issue.

stylesheet/firebase-ui.css
Our demo app has * {box-sizing: border-box} set, so I didn't catch it there.
=> Fix box-sizing on form actions

stylesheet/firebase-ui.css
I imported the auth ui css into my JS module, letting the css-loader webpack module handle it, but it found some badly formatted urls and gave me some parsing errors. I've edited the css and webpack is much happier now.
=> corrected a few invalid background img urls

changelog.txt, demo/public/index.html, demo/public/widget.html, package.json
Updated changelog for 2.4.1 release and incremented minimum firebase js version to include localized APIs.
=> Updated changelog for 2.4.1 release

package-lock.json, package.json
This version uses npm marked package >= 0.3.9 which has a security vulnerability in version 0.3.6.
=> Updates closure-builder version to ^2.2.34.

README.md
Fixed isPendingRedirect documentation
=> Update README.md -  isPendingRedirect

README.md, demo/public/app.js, demo/public/index.html, javascript/widgets/authui.js, javascript/widgets/authui_test.js, javascript/widgets/handler/callback.js, javascript/widgets/handler/callback_test.js, javascript/widgets/handler/common.js, javascript/widgets/handler/emailmismatch.js, javascript/widgets/handler/emailmismatch_test.js, javascript/widgets/handler/federatedlinking_test.js, javascript/widgets/handler/passwordlinking.js, javascript/widgets/handler/passwordlinking_test.js, javascript/widgets/handler/passwordsignin_test.js, translations/id.xtb
- Expose firebase.auth.UserCredential Auth result via new signInWithAuthResult callback.
=> SignInWithAuthResult callback

package-lock.json, package.json
Keeps it as devDependency as we depend on it for our unit tests.
=> Makes firebase a peerDependency instead of a dependency.

README.md
Updates README with explanation on known issue when 3rd party cookies are blocked.
=> 3rd party cookies being disabled known issue

gulpfile.js, package-lock.json, package.json
This pull request fixes:  
https://github.com/firebase/firebaseui-web/issues/82  
by copying css build transformation from material-design-lite build script:  
https://github.com/google/material-design-lite/blob/3b749f1/gulpfile.babel.js#L135
=> material design lite svg integration

javascript/utils/util.js, javascript/widgets/config.js, javascript/widgets/config_test.js
fixed the issue that cordova opens webview instead of system browser
=> fixed the issue that cordova opens webview instead of system browser

soy/elements.soy
=> Fix typo on GitHub sign-in button

README.md
This works locally but currently can't be used in production unless you are already on the whitelist. I think it's important that people know this before developing and testing with this feature.
=> Added a note that One-Tap beta test program is currently closed.

javascript/widgets/config.js, javascript/widgets/config_test.js
providerName should default to providerId if not provided
=> providerName should default to providerId if not provided

README.md, javascript/utils/idp.js, javascript/utils/idp_test.js, javascript/widgets/authui.js, javascript/widgets/config.js, javascript/widgets/config_test.js, javascript/widgets/dispatcher_test.js, javascript/widgets/handler/callback_test.js, javascript/widgets/handler/common.js, javascript/widgets/handler/federatedredirect.js, javascript/widgets/handler/federatedredirect_test.js, javascript/widgets/handler/handler.js, javascript/widgets/handler/handler_test.js, package-lock.json
Support for skipping the nascar buttons screen when only using a single federated provider.
=> Support for skipping the nascar screen

demo/public/app.js
Changed positioning of curly bracket to reflect the style used throughout the rest of the file
=> Style correction

gulpfile.js, javascript/ui/element/listboxdialog.js, package-lock.json, package.json
1. Added a ES module for FirebaseUI, since the this pointer in function scope is not point to window/global object, pass the pointer to the IIFE wrapper. 
2. Updated the closure compiler/library version. 
3. Fixed an issue that this pointer is not passed to dismissDialog function. 
Test: 
1. Plain script: 
Tested with demo app in both chrome and egde(make sure dialog polyfill works): https://fir-ui-demo-84a6c.firebaseapp.com/
2. CJS module(chrome and edge): transpile and bundle with babel and webpack and test:
https://jsfiddle.net/wangti0806/xybwrume/13/
3.  ESM module(chrome and edge): transpile and bundle with babel and webpack and test:
https://jsfiddle.net/wangti0806/xybwrume/11/
=> provide ESM for FirebaseUI

javascript/widgets/config.js, javascript/widgets/config_test.js, javascript/widgets/handler/common.js, javascript/widgets/handler/federatedlinking_test.js, javascript/widgets/handler/federatedsignin_test.js
Support login custom parameter for github.
=> Support login custom parameter for github.

README.md, changelog.txt
=> Release note for v4.1.0

.travis.yml, README.md, changelog.txt, javascript/utils/account_test.js, javascript/utils/actioncodeurlbuilder.js, javascript/utils/actioncodeurlbuilder_test.js, javascript/utils/redirectstatus.js, javascript/utils/redirectstatus_test.js, javascript/utils/storage.js, javascript/utils/storage_test.js, javascript/widgets/authui.js, javascript/widgets/authui_test.js, javascript/widgets/dispatcher_test.js, javascript/widgets/handler/common.js, javascript/widgets/handler/common_test.js, javascript/widgets/handler/emaillinksignincallback.js, javascript/widgets/handler/emaillinksignincallback_test.js, javascript/widgets/handler/testhelper.js, package-lock.json, package.json
Added support for multi-tenant in FirebaseUI.
=> multi-tenant support in firebaseui

README.md
=> Missing , in README

buildtools/publish.sh
added the ability to auto bump the version number in readme file
=> added the ability to auto bump the version number in readme file

README.md, buildtools/publish.sh
manually bump the version to 4.4 in readme and fixed the publish script
=> manually bump the version to 4.4 in readme and fixed the publish script

stylesheet/imports.css
=> Leverage the font-display CSS feature

gulpfile.js
Updates import from:
`import * as firebase from 'firebase/app'`
to
`import firebase from 'firebase/app'`
https://github.com/firebase/firebaseui-web/issues/771
=> fix: Update ES6 firebase/app import

javascript/widgets/config.js, javascript/widgets/config_test.js
Replace blacklist and whitelist with disallowlist and allowlist when possible.
=> fix: Replace with respectful terms

package.json
This is a necessary step for b/165671830
=> Bump firebase dev dependency version number to 8.2.4

buildtools/gen_all_tests_js.py, buildtools/gen_test_html.py, javascript/ui/page/selecttenant_test.js, package-lock.json, package.json
Fixes HTML test generation to support `goog.module()` and take into account newlines
and spaces in `goog.provide()`.
Fixes dependencies with high security vulnerabilities.
Updates python print statements.
=> fix: fixes broken tests

buildtools/container/Dockerfile
Update NPM version to 6.14.13 according to release [notes](https://nodejs.org/en/download/releases/) to match with node 14.17.3
=> Dockerversion

demo/public/index.html
The changes fixes and do `auth` settings form UI more user-friendly.
Now you could change checkbox state by clicking on the correspond `label`.
The fixed behavior is better to see on the before/after examples below.
| Before  | After |
| ------------- | ------------- |
| https://user-images.githubusercontent.com/3241812/151663838-45ee04af-2e1f-4a62-8863-b3d58c91fdfd.mov | https://user-images.githubusercontent.com/3241812/151663939-69d339de-3e2b-4bcb-9890-5141eca1448b.mov |
=> Fix behavior of checkbox selecting on `auth` settings form

README.md
Follow up from https://github.com/firebase/firebaseui-web/pull/982
=> Update README.md to use Firebase JS version 9.13.0 when using CDN

packages/angular/package.json, packages/angular/src/lib/auth/forms/sign-in-auth-form/sign-in-auth-form.component.ts, packages/angular/src/lib/components/form/form.component.ts, pnpm-lock.yaml
This PR upgrades tanstack form, allowing us to create composed form components
=> refactor(angular): Upgrade tanstack form
